Repository camunda-community-hub/camunda-cloud-go-client, pull requests merged in 2021-02, with the labels that each got.

#6 feature: creating cluster all request
  pkg/cc/client/client.go
  pkg/cc/client/types.go
Labels: size/M

#8 Verifying if cluster name already exists
  main.go
  pkg/cc/client/client.go
  pkg/cc/client/errors.go
Labels: size/M

#5 Add cobra CLI tool
  LICENSE
  cmd/clusters.go
  cmd/root.go
  go.mod
  go.sum
  main.go
  pkg/cc/client/client.go
Labels: size/XL

#10 Added lifecycle and community extension badges
  README.md
Labels: documentation, size/XS
